name: Print Messages on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  print-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set and print environment secret
        env:
          MY_SECRET: ${{ secrets.ENV_SECRET }}
        run: echo "This is my secret $MY_SECRET"

      - name: Set and print environment variable
        env:
          MY_ENV_VARIABLE: ${{ vars.ENV_VARIABLE }}
        run: echo "This is my env variable $MY_ENV_VARIABLE"
